name: GrappleTimer
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  developmentLanguage: en
  xcodeVersion: "15.0"
  
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    ENABLE_PREVIEWS: YES
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_LSApplicationQueriesSchemes: ["spotify"]
    INFOPLIST_KEY_UIBackgroundModes: ["audio"]
    INFOPLIST_KEY_NSUserActivityTypes: ["StartBJJTimerIntent"]
    INFOPLIST_KEY_CFBundleDisplayName: "Grapple Timer"
    PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.GrappleTimer
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  GrappleTimer:
    type: application
    platform: iOS
    sources:
      - path: GrappleTimer
        excludes:
          - "**/.DS_Store"
          - "**/Tests"
        createIntermediateGroups: true
    resources:
      - path: GrappleTimer/Resources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_NAME: GrappleTimer
        INFOPLIST_FILE: GrappleTimer/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    dependencies: []
    preBuildScripts: []
    postBuildScripts: []

  GrappleTimerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GrappleTimerTests
    dependencies:
      - target: GrappleTimer
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/GrappleTimer.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/GrappleTimer"

schemes:
  GrappleTimer:
    build:
      targets:
        GrappleTimer: all
    run:
      config: Debug
      commandLineArguments:
        "-FIRAnalyticsDebugEnabled": false
    test:
      config: Debug
      targets:
        - GrappleTimerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release